#!/bin/bash
{%- set server = pillar.billometer.server %}

NAME="billometer"
DJANGODIR=/srv/billometer/site
USER=billometer
GROUP=billometer
NUM_WORKERS={{ server.workers }}
DJANGO_SETTINGS_MODULE=billometer.settings
DJANGO_WSGI_MODULE=wsgi

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /srv/billometer/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind={{ server.bind.address }}:{{ server.bind.port }}